import type { Metadata } from "next";
import { outfit } from "./fonts";
import "./globals.css";
import Image from "next/image";
import styles from "./page.module.css";
import Link from "next/link";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Separator({ height = 1 }) {
  return (
    <hr
      style={{
        backgroundColor: "white",
        marginBlock: "0.8rem",
        height: height,
        border: "none",
      }}
    />
  );
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={outfit.className}>
      <body>
        <Providers>
          <section>
            {/* Include shared UI here e.g. a header or sidebar */}
            <nav>
              <div id="header" className={styles.header}>
                <Link href="/">
                  <div id="header_logo" className={styles.headerLogo}>
                    <Image
                      src="/fknm_logo.png"
                      alt="FKNM Logo"
                      width={70}
                      height={70}
                      priority
                    />
                  </div>
                </Link>
                <Link id="header_title" href="/">
                  <p>Feeding Kids, Nourishing Minds</p>
                </Link>
              </div>

              <div id="nav_bar" className={styles.navigationbar}>
                <div className={styles.navigationbarContent}>
                  <Link
                    id="nav_school_food_programs"
                    href="/school_food_programs/"
                  >
                    <p>School Food Programs</p>
                  </Link>

                  <div id="nav_research" className={styles.researchNavItem}>
                    Research
                    <div
                      id="nav_research_submenu"
                      className={styles.navBarSubMenu}
                    >
                      <Link id="nav_intake_visuals" href="/intake_visuals/">
                        Intake Visuals
                      </Link>
                      <Separator />
                      <Link
                        id="nav_measurement_tool_assessment"
                        href="/measurement_tool_assessment/"
                      >
                        Measurement Tool Assessment
                      </Link>
                      <Separator />
                    </div>
                  </div>

                  <Link id="nav_news" href="/news/">
                    News
                  </Link>
                  <div id="nav_publications" className={styles.researchNavItem}>
                    Publications
                    <div
                      id="nav_publications_submenu"
                      className={styles.navBarSubMenu}
                    >
                      <Link id="nav_manuscripts" href="/manuscripts/">
                        Manuscripts
                      </Link>
                      <Separator />
                      <Link id="nav_presentations" href="/presentations/">
                        Presentations
                      </Link>
                      <Separator />
                    </div>
                  </div>
                  <Link id="nav_about_fknm" href="/about_fknm/">
                    About FKNM
                  </Link>
                </div>
              </div>
            </nav>

            {children}
          </section>
        </Providers>
      </body>
    </html>
  );
}
